Mongodb subscriber
opentracing-contrib/ruby-mongodb-instrumentation pull request #1
Opened 2018-11-08 18:35 UTC by achandras

2018-11-09 05:46 UTC, mpetazzoni commented
This LGTM. @keitwb if you agree please squash and merge.

2018-11-17 01:04 UTC, mpetazzoni requested changes

2018-11-17 01:04 UTC, mpetazzoni commented on lib/mongodb/instrumentation/command_subscriber.rb
> +          'component' => 'mongodb-instrumentation',
This should just be `mongodb`, or `ruby-mongodb` I think

2018-11-17 01:04 UTC, mpetazzoni commented on lib/mongodb/instrumentation/command_subscriber.rb
> +          'command_name' => event.command_name,
You might want to namespace those additional tags:

```
mongo.command.name
mongo.operation.id
mongo.request.id
```

2018-11-17 01:04 UTC, mpetazzoni commented on lib/mongodb/instrumentation/command_subscriber.rb
> +        span.set_tag("duration", event.duration)
I'd recommend calling this `took`, to differentiate from the span's duration. Also, what is the unit here? If it's milliseconds for example, call `took.ms`.

2018-11-17 01:04 UTC, mpetazzoni commented on lib/mongodb/instrumentation/command_subscriber.rb
> +        span.set_tag("duration", event.duration)
Same comment about duration

2018-11-17 01:04 UTC, mpetazzoni commented on lib/mongodb/instrumentation/command_subscriber.rb
> +        span.log_kv(key: "message", value: event.message)
Use the `error.msg` event key

2018-11-17 01:27 UTC, achandras commented on lib/mongodb/instrumentation/command_subscriber.rb
> +        span.log_kv(key: "message", value: event.message)
Is it OK to deviate from the opentracing tags spec here? I think they just have the `message` tag for errors.

2018-11-17 06:14 UTC, mpetazzoni commented on lib/mongodb/instrumentation/command_subscriber.rb
> +        span.log_kv(key: "message", value: event.message)
You're right, looks like they do have a spec around this: https://github.com/opentracing/specification/blob/master/semantic_conventions.md#captured-errors

Keep as is then

2018-11-21 17:14 UTC, mpetazzoni approved these changes

2018-11-21 17:26 UTC, merged